# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Web

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Web and Deploy
    runs-on: ubuntu-latest
    env: 
      BASE_HREF: /${{ github.event.repository.name }}/
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
          channel: 'stable'
      - run: flutter build web --release --base-href $BASE_HREF
      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{github.ref == 'refs/heads/master' }}
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
